export const ORGANIZATION_REPOSITORY = Symbol('ORGANIZATION_REPOSITORY');
export const ORGANIZATION_MEMBER_REPOSITORY = Symbol('ORGANIZATION_MEMBER_REPOSITORY');
export const ORGANIZATION_INVITATION_REPOSITORY = Symbol('ORGANIZATION_INVITATION_REPOSITORY');
