packages:
  - "apps/*"

overrides:
  lodash: ">=4.17.24"
  multer: ">=2.2.0"
  js-yaml: ">=4.1.2"

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  argon2: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
