services:
  postgres:
    ports:
      - "15433:5432"

  redis:
    ports:
      - "16379:6379"

  minio:
    ports:
      - "19000:9000"
      - "19001:9001"

  backend:
    ports:
      - "13000:3000"
