export const EMPLOYEE_REPOSITORY = Symbol('EMPLOYEE_REPOSITORY');
export const ROLE_PERMISSION_REPOSITORY = Symbol('ROLE_PERMISSION_REPOSITORY');
export const ROLE_REPOSITORY = Symbol('ROLE_REPOSITORY');
