/**
 * Generates 6-digit numeric OTPs and produces SHA-256 digests for storage at
 * rest (ADR-022 Decision #6/#14). Deliberately a separate port from
 * `OpaqueTokenService`: a 6-digit code has a materially different
 * entropy/attempt-limiting profile than a 256-bit opaque token, so it is not
 * generated by `Sha256OpaqueTokenService.generate()` (which produces
 * base64url strings, the wrong shape entirely).
 */
export interface OtpService {
  /** Cryptographically secure 6-digit numeric code, zero-padded (e.g. "004821"). */
  generate(): string;
  hash(code: string): string;
  verify(code: string, storedHash: string): boolean;
}
